# See the writing guide of rbs: https://github.com/ruby/rbs#guides#
module Yabeda
  module Resque
    VERSION: String

    def self.install!: () -> void

    def self.monitor_delayed?: () -> bool
  end
end
